export const ADD_NOTE: any = "ADD_NOTE"
export const UPDATE_NOTE = "UPDATE_NOTE"
export const ADD_NOTE_TAG = "ADD_TAG"
export const UPDATE_TAG = "UPDATE_TAG"
export const ADD_ITEM: string = "ADD_ITEM"
export const ADD_ITEM_CATEGORY: string = "ADD_ITEM_CATEGORY"